define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "Projects": "Projects",
    "MyCV" : "My CV",
    "EditCV": "Edit my CV",
    "OverallIntroduction": "Overall introduction",
    "Languages": "Languages",
    "Education": "Education",
    "Customers": "Customers",
    "Delete": "Delete",
    "Add": "Add",
    "BusinessSector": "Business sector",
    "CreateBusinessSector": "Create a business sector",
    "SelectFile": "Select File",
    "Name": "Name",
    "Cancel": "Cancel",
    "Save": "Save",
    "FieldRequired" : "This field is required",
    "Edit" : "Edit",
    "FilterByName" : "Filter by name",
    "Customer" : "Customer",
    "Project" : "Project",
    "Type" : "Type",
    "Title" : "Title",
    "OutsideCustomer" : "Outside Customer",
    "ProjectType" : "Project Type",
    "Description" : "Description",
    "Technos" : "Technos",
    "Techno" : "Techno",
    "CustomerNotFoundMsg" : "If you can't find the customer, use the 'Outside customer' field",
    "Certifications" : "Certifications",
    "Interventions" : "Interventions",
    "ActivityStartDate" : "Activity start date",
    "JobTitle" : "Job title",
    "Introduction" : "Introduction",
    "Skills" : "Skills",
    "Level" : "Level",
    "Language" : "Language",
    "Languages" : "Languages",
    "Softskill" : "Softskill",
    "Softskills" : "Softskills",
    "Graduations" : "Graduations",
    "Graduation" : "Graduation",
    "Diploma" : "Diploma",
    "School" : "School",
    "GraduationDate" : "Graduation date",
    "Branch" : "Branch",
    "ServiceLine" : "Service line",
    "Company" : "Company",
    "Certification" : "Certification",
    "CertifNotFoundMsg" : "Fill the field below to create a certification",
    "Intervention" : "Intervention",
    "Interventions" : "Interventions",
    "Date" : "Date",
    "ProjectNotFoundMsg" : "Use the plus to create a project",
    "AddProject" : "Add a project",
    "StartingDate" : "Starting date",
    "Duration" : "Duration",
    "Role" : "Role",
    "Roles" : "Roles",
    "Mission" : "Mission",
    "IncludeInCv" : "Include in CV",
    "Yes" : "Yes",
    "No" : "No"
  }
});