define([], function() {
    return {
      "Projects": "Projets",
      "MyCV": "Mes CV",
      "EditCV": "Modifier mon CV",
      "OverallIntroduction": "Présentation générale",
      "Languages": "Langues",
      "Education": "Formation",
      "Customers": "Clients",
      "Delete": "Supprimer",
      "Add": "Ajouter",
      "BusinessSector": "Secteur d'activité",
      "CreateBusinessSector" : "Créer un secteur d'activité",
      "SelectFile" : "Choisir Fichier",
      "Name" : "Nom",
      "Cancel" : "Annuler",
      "Save": "Enregistrer",
      "FieldRequired" : "Ce champ est requis",
      "Edit" : "Modifier",
      "FilterByName" : "Filtrer par nom",
      "Customer" : "Client",
      "Project" : "Projet",
      "Type" : "Type",
      "Title" : "Titre",
      "OutsideCustomer" : "Client externe",
      "ProjectType" : "Type de projet",
      "Description" : "Description",
      "Technos" : "Technos",
      "Techno" : "Techno",
      "CustomerNotFoundMsg" : "Si vous ne trouvez pas le client, utilisez le champ 'Client externe'",
      "Certifications" : "Certifications",
      "Interventions" : "Interventions",
      "ActivityStartDate" : "Date de début d'activité",
      "JobTitle" : "Intitulé du poste",
      "Introduction" : "Présentation",
      "Skills" : "Compétences",
      "Level" : "Niveau",
      "Language" : "Langue",
      "Languages" : "Langues",
      "Softskill" : "Compétence",
      "Softskills" : "Compétences",
      "Graduations" : "Cursus de formation",
      "Graduation" : "Cursus de formation",
      "Diploma" : "Diplôme",
      "School" : "Ecole",
      "GraduationDate" : "Date d'obtention",
      "Branch" : "Entité",
      "ServiceLine" : "Pôle",
      "Company" : "Entreprise",
      "Certification" : "Certification",
      "CertifNotFoundMsg" : "Remplissez les champs ci-dessous pour créer une certification",
      "Intervention" : "Intervention",
      "Interventions" : "Interventions",
      "Date" : "Date",
      "ProjectNotFoundMsg" : "Utilisez le plus pour créer un projet",
      "AddProject" : "Ajouter un projet",
      "StartingDate" : "Date de début",
      "Duration" : "Durée",
      "Role" : "Rôle",
      "Roles" : "Rôles",
      "Mission" : "Mission",
      "IncludeInCv" : "Inclure dans le CV",
      "Yes" : "Oui",
      "No" : "Non"
    }
  });