declare interface ITeamsAppsCvWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  Projects : string;
  MyCV : string;
  EditCV : string;
  OverallIntroduction : string;
  Languages : string;
  Education : string;
  Customers : string;
  Delete : string;
  Add : string;
  BusinessSector: string;
  CreateBusinessSector : string;
  SelectFile : string;
  Name : string;
  Cancel : string;
  Save : string;
  FieldRequired : string;
  Edit : string;
  FilterByName : string;
  Customer : string;
  Project : string;
  Type : string;
  Title : string;
  OutsideCustomer : string;
  ProjectType : string;
  Description : string;
  Technos : string;
  Techno : string;
  CustomerNotFoundMsg : string;
  Certifications : string;
  Interventions : string;
  ActivityStartDate : string;
  JobTitle : string;
  Introduction : string;
  Skills : string;
  Level : string;
  Language : string;
  Languages : string;
  Softskill : string;
  Softskills : string;
  Graduations : string;
  Graduation : string;
  Diploma : string;
  School : string;
  GraduationDate : string;
  Branch : string;
  ServiceLine : string;
  Company : string;
  Certification : string;
  CertifNotFoundMsg : string;
  Intervention : string;
  Interventions : string;
  Date : string;
  ProjectNotFoundMsg : string;
  AddProject : string;
  StartingDate : string;
  Duration : string;
  Role : string;
  Roles : string;
  Mission : string;
  IncludeInCv : string;
  Yes : string;
  No : string;
}

declare module 'TeamsAppsCvWebPartStrings' {
  const strings: ITeamsAppsCvWebPartStrings;
  export = strings;
}
